title: Yuriy Lesyuk - GitHub Pages
email: yuriylesyuk@gmail.com
description: >-
  YL Github Pages!
baseurl: /
url: https://yuriylesyuk.github.io/

show_full_navigation: true

github_username:  yuriylesyuk

# Build settings
remote_theme: "mmistakes/minimal-mistakes@4.26.1"
