title: Yuriy Lesyuk
email: yuriylesyuk@gmail.com
description: >-
  YL Github Pages

github_username:  yuriylesyuk

minimal_mistakes_skin: contrast
search: true


# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes@4.26.1

include: 
  - _pages

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache
